- alias: Switch to audio input
  trigger:
    - platform: state
      entity_id: media_player.sound_system
      to: "playing"
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.avr
    - service: media_player.select_source
      data:
        entity_id: media_player.avr
        source: "Chromecast"
    - service: media_player.media_pause
      data:
        entity_id: media_player.tv


- alias: Switch to TV input
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: "playing"
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.avr
    - service: media_player.select_source
      data:
        entity_id: media_player.avr
        source: "Media Player"
    - service: media_player.media_pause
      data:
        entity_id: media_player.sound_system


- alias: Alarm if door opens when we're not here
  trigger:
    platform: state
    entity_id: sensor.door_living_room
    to: 'open'
  condition:
    condition: template
    value_template: "{{ states.climate.living_room.attributes.min_temp <= 60 }}"
  action:
    service: notify.twilio
    data:
      message: 'Your front door has opened'
      target:
        - !secret my_number


- alias: Google Home Night Volume
  trigger:
    platform: time
    after: '23:00:00'
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_home
      data:
        volume_level: .35


- alias: Google Home Day Volume
  trigger:
    platform: time
    after: '10:00:00'
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_home
      data:
        volume_level: .55


- alias: turn bathroom lights on low on hallway motion at night
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_3_10
    from: '0'
    to: '8'
  condition:
    condition: state
    entity_id: light.main_light
    state: 'off'
  action:
    service: light.turn_on
    entity_id: light.bathroom
    data:
      brightness: 5


- alias: turn bathroom lights on low on hallway motion at night
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_3_10
    from: '0'
    to: '8'
  condition:
    condition: state
    entity_id: light.main_light
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom
    data:
      brightness: 200


- alias: turn bathroom lights off when no motion
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_3_10
    from: '8'
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.bathroom
