- id: switch_to_audio_input
  alias: Switch to audio input
  trigger:
    - platform: state
      entity_id: media_player.sound_system
      to: "playing"
    - platform: state
      entity_id: media_player.everything
      to: "playing"
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.denon_avrs710w
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrs710w
        source: "Chromecast"
    - service: media_player.media_pause
      data:
        entity_id: media_player.tv


- id: switch_to_tv_input
  alias: Switch to TV input
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: "playing"
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.denon_avrs710w
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrs710w
        source: "Media Player"
    - service: media_player.media_pause
      data:
        entity_id: media_player.sound_system


- id: door_alarm
  alias: Alarm if door opens when we're not here
  trigger:
    platform: state
    entity_id: sensor.door_living_room
    to: 'open'
  condition:
    condition: template
    value_template: "{{ states.climate.living_room.attributes.min_temp <= 60 }}"
  action:
    service: notify.twilio_sms
    data:
      message: 'Your front door has opened'
      target:
        - !secret my_number


- id: home_night_volume
  alias: Google Home Night Volume
  trigger:
    platform: time
    at: '23:00:00'
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_home
      data:
        volume_level: .35


- id: home_day_volume
  alias: Google Home Day Volume
  trigger:
    platform: time
    at: '10:00:00'
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_home
      data:
        volume_level: .55


### Bathroom lights motion automations

- id: hallway_night
  alias: turn bathroom lights on low on hallway motion at night
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 0.0
      - condition: state
        entity_id: sensor.living_room_is_dim
        state: 'yes'
  action:
    service: light.turn_on
    entity_id: light.bathroom
    data:
      brightness: 5


- id: hallway_day
  alias: turn bathroom lights on high on hallway motion during the day
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    to: '8'
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        above: 0.0
      - condition: state
        entity_id: sensor.living_room_is_dim
        state: 'no'
  action:
    service: light.turn_on
    entity_id: light.bathroom
    data:
      brightness: 200


- id: bathroom_no_motion
  alias: turn bathroom lights off when no motion
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '8'
    to: '0'
    for:
      minutes: 41  # 45 total minutes before shutdown
  condition:
    condition: or
    conditions:
      - condition: time
        after: "00:00:00"
        before: "07:30:00"
      - condition: time
        after: "12:00:00"
        before: "22:00:00"
  action:
    service: light.turn_off
    entity_id: light.bathroom


- id: reset_light_brightness_at_daylight
  alias: Lights -- reset brightness at daylight
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
        brightness: 254
    - service: light.turn_on
      entity_id: group.kitchen_lights
      data:
        brightness: 254
    - service: light.turn_off
      entity_id: group.living_room_lights
    - service: light.turn_off
      entity_id: group.kitchen_lights
