homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.9728
  longitude: -87.6616
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 179
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  server_port: !secret port

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
# sun:

# Weather Prediction
sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - icon
      - temperature
      - hourly_summary
  - platform: iss

media_player:
  - platform: cast
  - platform: denonavr
    name: avr
    host: 192.168.1.43

light:
  platform: hue
  host: 192.168.1.47

tts:
  - platform: google

ecobee:
  api_key: !secret ecobee_api_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

automation:
  - alias: Switch to audio input
    trigger:
      - platform: state
        entity_id: media_player.sound_system
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Chromecast"
      - service: media_player.media_pause
        data:
          entity_id: media_player.tv


  - alias: Switch to TV input
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Media Player"
      - service: media_player.media_pause
        data:
          entity_id: media_player.sound_system
