homeassistant:
  name: Home
  latitude: 41.9728
  longitude: -87.6616
  elevation: 179
  unit_system: imperial
  time_zone: America/Chicago

frontend:

http:
  api_password: !secret api_password
  server_port: !secret port

config:
updater:
discovery:
conversation:
history:
logbook:

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - icon
      - temperature
      - hourly_summary

binary_sensor:
  - platform: iss
  - platform: aurora

media_player:
  - platform: cast
  - platform: denonavr
    name: avr
    host: 192.168.1.43

light:
  platform: hue
  host: 192.168.1.47

tts:
  - platform: google

ecobee:
  api_key: !secret ecobee_api_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

zwave:
  usb_path: /dev/ttyACM0

automation:
  - alias: Switch to audio input
    trigger:
      - platform: state
        entity_id: media_player.sound_system
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Chromecast"
      - service: media_player.media_pause
        data:
          entity_id: media_player.tv


  - alias: Switch to TV input
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Media Player"
      - service: media_player.media_pause
        data:
          entity_id: media_player.sound_system


  - alias: Google Home Night Volume
    trigger:
      platform: time
      after: '23:00:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.kitchen_home
        data:
          volume_level: .35

  - alias: Google Home Day Volume
    trigger:
      platform: time
      after: '10:00:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.kitchen_home
        data:
          volume_level: .75
