homeassistant:
  name: Home
  latitude: 41.9728
  longitude: -87.6616
  elevation: 179
  unit_system: imperial
  time_zone: America/Chicago

frontend:

http:
  api_password: !secret api_password
  server_port: !secret port

config:
updater:
discovery:
conversation:
history:
logbook:

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - icon
      - temperature
      - hourly_summary

binary_sensor:
  - platform: iss
  - platform: aurora

media_player:
  - platform: cast
  - platform: denonavr
    name: avr
    host: 192.168.1.43

light:
  platform: hue
  host: 192.168.1.47

tts:
  - platform: google

ecobee:
  api_key: !secret ecobee_api_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

zwave:
  usb_path: /dev/ttyACM0

group:
  default_view:
    view: yes
    entities:
      - group.lights_abstracted
      - group.weather
      - group.climate
      - media_player.sound_system
      - media_player.tv

  lights:
    view: yes
    entities:
      - group.living_room
      - group.kitchen
      - group.bathroom
      - group.bedroom

  lights_abstracted:
    name: Lights
    entities:
      - light.kitchen
      - light.living_room
      - light.bathroom
      - light.bedroom

  climate:
    name: Climate
    entities:
      - climate.living_room
      - sensor.living_room_humidity
      - sensor.living_room_nest_protect_smoke_status

  weather:
    name: Weather
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_hourly_summary

  media:
    name: Media
    view: yes
    entities:
      - media_player.avr
      - media_player.sound_system
      - media_player.tv
      - media_player.kitchen_home

  space:
    name: space
    view: yes
    entities:
      - binary_sensor.aurora_visibility
      - binary_sensor.iss

  kitchen:
    name: Kitchen
    entities:
      - light.kitchen_1
      - light.kitchen_2
      - light.kitchen_3
      - light.kitchen_4
      - light.kitchen_5

  living_room:
    name: Living room
    entities:
      - light.desk_lamp
      - light.main_light

  bathroom:
    name: bathroom
    entities:
      - light.bathroom_1
      - light.bathroom_2

  bedroom:
    name: bedroom
    entities:
      - light.bedroom_lamp

automation:
  - alias: Switch to audio input
    trigger:
      - platform: state
        entity_id: media_player.sound_system
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Chromecast"
      - service: media_player.media_pause
        data:
          entity_id: media_player.tv


  - alias: Switch to TV input
    trigger:
      - platform: state
        entity_id: media_player.tv
        to: "playing"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.avr
      - service: media_player.select_source
        data:
          entity_id: media_player.avr
          source: "Media Player"
      - service: media_player.media_pause
        data:
          entity_id: media_player.sound_system


  - alias: Google Home Night Volume
    trigger:
      platform: time
      after: '23:00:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.kitchen_home
        data:
          volume_level: .35

  - alias: Google Home Day Volume
    trigger:
      platform: time
      after: '10:00:00'
    action:
      - service: media_player.volume_set
        entity_id: media_player.kitchen_home
        data:
          volume_level: .75
