homeassistant:
  name: Home
  latitude: 41.9728
  longitude: -87.6616
  elevation: 179
  unit_system: imperial
  time_zone: America/Chicago

frontend:

http:
  api_password: !secret api_password
  server_port: !secret port

config:
updater:
discovery:
conversation:
history:
logbook:

sun:

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - icon
      - temperature
      - hourly_summary
  - platform: template
    sensors: !include custom_sensors.yaml

binary_sensor:
  - platform: iss
  - platform: aurora

media_player:
  - platform: cast
  - platform: denonavr
    name: avr
    host: 192.168.1.43

light:
  platform: hue
  host: 192.168.1.47

tts:
  - platform: google

ecobee:
  api_key: !secret ecobee_api_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  platform: twilio_sms
  from_number: !secret twilio_from_number

zwave:
  usb_path: /dev/ttyACM0

script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml
