version: 2.0
jobs:
  build:
    docker:
      - image: homeassistant/home-assistant:latest
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install homeassistant
            python3 -m pip uninstall botocore boto3 -y
            echo "${SECRETS}" > secrets.yaml
            sed -i 's/--- /\n/g' secrets.yaml
            hass --script check_config -c .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
