version: 2.0
jobs:
  build:
    docker:
      - image: homeassistant/home-assistant:latest
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install homeassistant
            python3 -m pip uninstall botocore boto3 -y
            echo "${SECRETS}" > secrets.yaml
            sed -i 's/--- /\n/g' secrets.yaml
            hass --script check_config -c .
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'cd ./.homeassistant && git stash && git pr && git stash pop'
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'hass --script check_config'
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'rm -f ~/dasher/config/config.json && cp bootstrap/dasher/config.json ~/dasher/config/config.json'
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'sed -i "s/PASSWORD/${HA_PASSWORD}/g" ~/dasher/config/config.json'
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'sudo systemctl restart home-assistant.service'
            ssh "${DEPLOY_USER}"@"${DEPLOY_SERVER}" 'sudo systemctl restart dasher.service'


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
